import Head from "next/head";
import Image from "next/image";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-[56%] text-center mx-auto">
          <div className="mx-auto w-24 aspect-square rounded-full bg-[#005AC1] bg-opacity-10">
            <img src="/memoji.png" className="mx-1 mt-2 p-1" />
          </div>
          <h3 className="mb-5 mt-10">Hi, I&apos;m Manas Malla</h3>
          <h1 className="text-6xl leading-[1.3em]">
            <span className="underline decoration-[#005AC1]/20 decoration-dashed">
              Building
            </span>{" "}
            solutions
            <br />
            is my ikigai.
          </h1>
          <h2 className="text-2xl font-light mb-14 mt-10">
            <span className="font-semibold">
              a Designer, Developer, Speaker, Student and Tech Geek
            </span>
            <br />I specialise in Swift Development, UI/UX design, Android
            development, Flutter Development and open-source contribtion
          </h2>
          <button className="bg-black text-white px-12 py-3 rounded-full uppercase">
            Connect with Me
          </button>
        </div>
        <div className="my-28">
          <div className="flex gap-6">

            <div className="w-[40%] aspect-[0.974137931034483] h-max">
              <img src="asj-manas.jpg" className="w-full aspect-[2.1] object-cover object-top mb-5 rounded-md shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]"/>
              <img src="gds-manas.jpg" className="w-full aspect-[2.025089605734767] object-cover rounded-md shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />
            </div>

            <img src="image-main.jpg" className="w-[27%] h-max rounded-md shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />

            <div className="w-[34%] aspect-[square] h-max">
              <img src="https://pbs.twimg.com/media/FVB8pcGagAAun41?format=jpg&name=4096x4096" className="w-full aspect-[1.385] object-cover mb-5 rounded-md shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />
              <img src="dare-to-be-fearless.jpg" className="w-full aspect-[2.36] object-cover rounded-md object-[0%,10%] shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />
            </div>

          </div>
          <div className="flex gap-6 mt-4">
            
            <img src="iwd-manas.jpg" className="w-[60%] aspect-[3.3] object-cover rounded-md object-top shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />
             <img src="wed-manas.jpeg" className="w-[18%] aspect-[1.8] object-cover rounded-md shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />
            <img src="temple-manas.jpg" className="w-[22%] aspect-[1.6] object-cover rounded-md shadow-[0_4px_32px_4px_rgba(0,0,0,0.16)]" />
          </div>

        </div>
      </main>
    </>
  );
}
